# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wine_quality_pb2 as wine__quality__pb2


class WineQualityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.wine_quality = channel.unary_unary(
                '/WineQuality/wine_quality',
                request_serializer=wine__quality__pb2.WineQualityRequest.SerializeToString,
                response_deserializer=wine__quality__pb2.WineQualityResponse.FromString,
                )


class WineQualityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def wine_quality(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WineQualityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'wine_quality': grpc.unary_unary_rpc_method_handler(
                    servicer.wine_quality,
                    request_deserializer=wine__quality__pb2.WineQualityRequest.FromString,
                    response_serializer=wine__quality__pb2.WineQualityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WineQuality', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WineQuality(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def wine_quality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WineQuality/wine_quality',
            wine__quality__pb2.WineQualityRequest.SerializeToString,
            wine__quality__pb2.WineQualityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
